In [ ]:
# 1. Import libraries
import pandas as pd
import joblib
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

In [10]:
# 2. Load dataset
df = pd.read_csv("data.csv")
df.head()

,Weather_Condition,Road_Surface_Condition,Light_Condition,Road_Type,Junction_Type,Area_Type,Traffic_Level,Vehicle_Type,Speed_Limit,Number_of_Vehicles,Number_of_Casualties,Driver_Age,Driver_Experience_Years,Visibility_km,Time_of_Day,Day_of_Week,Accident_Severity
0,Clear,Wet,Daylight,Urban Road,NaN,Urban,Low,Car,100,5,4,52,12,11.8,Afternoon,Friday,Serious
1,Rain,Dry,Dark - lights on,Highway,NaN,Urban,Low,Bus,50,4,1,69,30,5.0,Morning,Friday,Minor
2,Rain,Wet,Daylight,Highway,T-Junction,Rural,Medium,Van,60,5,1,59,33,11.8,Morning,Monday,Minor
3,Clear,Dry,Dawn/Dusk,Urban Road,T-Junction,Urban,Medium,Car,100,3,5,20,28,9.0,Morning,Thursday,Fatal
4,Clear,Dry,Daylight,Rural Road,Roundabout,Urban,Medium,Car,50,4,2,37,36,11.2,Night,Monday,Minor

In [5]:
# 3. Clean the data
df = df.drop_duplicates()
df['Junction_Type'] = df['Junction_Type'].fillna('UnKnown')

In [6]:
# 4. Separate features and target
x = df.drop('Accident_Severity',axis=1)
y = df['Accident_Severity']

In [8]:
# 5. Convert categorical data into numbers
x = pd.get_dummies(x, drop_first=True)
x

,Speed_Limit,Number_of_Vehicles,Number_of_Casualties,Driver_Age,Driver_Experience_Years,Visibility_km,Weather_Condition_Fog,Weather_Condition_Rain,Weather_Condition_Snow,Weather_Condition_Windy,...,Vehicle_Type_Van,Time_of_Day_Evening,Time_of_Day_Morning,Time_of_Day_Night,Day_of_Week_Monday,Day_of_Week_Saturday,Day_of_Week_Sunday,Day_of_Week_Thursday,Day_of_Week_Tuesday,Day_of_Week_Wednesday
0,100,5,4,52,12,11.8,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,50,4,1,69,30,5.0,False,True,False,False,...,False,False,True,False,False,False,False,False,False,False
2,60,5,1,59,33,11.8,False,True,False,False,...,True,False,True,False,True,False,False,False,False,False
3,100,3,5,20,28,9.0,False,False,False,False,...,False,False,True,False,False,False,False,True,False,False
4,50,4,2,37,36,11.2,False,False,False,False,...,False,False,False,True,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595,50,4,1,20,32,6.8,False,False,False,False,...,True,True,False,False,False,False,False,False,False,False
596,40,3,3,26,3,8.5,False,False,False,False,...,False,True,False,False,False,False,True,False,False,False
597,40,3,3,28,37,13.3,True,False,False,False,...,True,False,False,False,False,False,False,False,False,False
598,30,3,5,35,5,3.6,False,True,False,False,...,True,False,False,False,False,False,False,False,False,True
599,100,4,1,39,13,5.0,False,False,False,False,...,False,False,True,False,False,False,False,True,False,False

In [11]:
# 6. Split the data
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=42, stratify=y)

In [ ]:
# 7. Train the model
model = RandomForestClassifier(n_estimators=200, random_state=42)
model.fit(x_train, y_train)

RandomForestClassifier(n_estimators=200, random_state=42)

In [18]:
# 8. Evaluate the model
y_pred = model.predict(x_test)
print("Accuracy:",accuracy_score(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Accuracy: 0.8

Classification Report:
              precision    recall  f1-score   support

       Fatal       0.80      0.25      0.38        16
       Minor       0.86      0.88      0.87        43
     Serious       0.76      0.89      0.82        61

    accuracy                           0.80       120
   macro avg       0.81      0.67      0.69       120
weighted avg       0.80      0.80      0.78       120

In [22]:
# 9. Sava model as .joblib
joblib.dump(model, "model.joblib")
print('Model saved successfully as model.joblib')

Model saved successfully as model.joblib